networks:
  loja-api:
    driver: bridge

services:
  Dbserver:
    container_name: app-db-v2
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    volumes:
      - mssql-data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw0rd!
    networks:
      - loja-api

  loja-api.webapi:
    container_name: "LojaApi"
    image: ${DOCKER_REGISTRY-}lojaapiwebapi
    build:
      context: .
      dockerfile: loja-api.endpoints/Dockerfile
    ports:
      - 8001:80
    depends_on:
      - Dbserver
    environment:
      - DB_HOST=Dbserver
      - DB_NAME=WEBAPI
      - DB_SA_PASSWORD=P@ssw0rd!
    networks:
      - loja-api

volumes:
  mssql-data:
