// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using loja_api.infra.Context;

#nullable disable

namespace loja_api.infra.Migrations
{
    [DbContext(typeof(ContextDB))]
    partial class ContextDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("loja_api.domain.Entities.Cupom", b =>
                {
                    b.Property<Guid>("CupomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CupomId");

                    b.ToTable("Cupom");
                });

            modelBuilder.Entity("loja_api.domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("loja_api.domain.Entities.Paymant", b =>
                {
                    b.Property<string>("PaymantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("CupomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("PaymantId");

                    b.HasIndex("CupomId")
                        .IsUnique();

                    b.HasIndex("IdUser");

                    b.ToTable("Paymant");
                });

            modelBuilder.Entity("loja_api.domain.Entities.Products", b =>
                {
                    b.Property<Guid>("IdProducts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityStorage")
                        .HasColumnType("int");

                    b.Property<string>("TypeProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProducts");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("loja_api.domain.Entities.Storage", b =>
                {
                    b.Property<Guid>("IdStorage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdProducts")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<double>("PriceBuy")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("IdStorage");

                    b.HasIndex("IdProducts");

                    b.ToTable("Storage");
                });

            modelBuilder.Entity("loja_api.domain.Entities.User", b =>
                {
                    b.Property<Guid>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("loja_api.domain.Entities.auxiliar.ProductsPaymant", b =>
                {
                    b.Property<string>("MarketCartId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("IdProducts")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("MarketCartId", "IdProducts");

                    b.HasIndex("IdProducts");

                    b.ToTable("ProductsPaymant");
                });

            modelBuilder.Entity("loja_api.domain.Entities.Cupom", b =>
                {
                    b.OwnsOne("loja_api.domain.Entities.auxiliar.Auditable", "Auditable", b1 =>
                        {
                            b1.Property<Guid>("CupomId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreateDate")
                                .HasColumnType("datetime2");

                            b1.Property<int>("CreatebyId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("UpdateDate")
                                .HasColumnType("datetime2");

                            b1.Property<int>("UpdatebyId")
                                .HasColumnType("int");

                            b1.HasKey("CupomId");

                            b1.ToTable("Cupom");

                            b1.WithOwner()
                                .HasForeignKey("CupomId");
                        });

                    b.Navigation("Auditable")
                        .IsRequired();
                });

            modelBuilder.Entity("loja_api.domain.Entities.Employee", b =>
                {
                    b.OwnsOne("loja_api.domain.Entities.auxiliar.Auditable", "Auditable", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreateDate")
                                .HasColumnType("datetime2");

                            b1.Property<int>("CreatebyId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("UpdateDate")
                                .HasColumnType("datetime2");

                            b1.Property<int>("UpdatebyId")
                                .HasColumnType("int");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employee");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.Navigation("Auditable")
                        .IsRequired();
                });

            modelBuilder.Entity("loja_api.domain.Entities.Paymant", b =>
                {
                    b.HasOne("loja_api.domain.Entities.Cupom", "Cupom")
                        .WithOne()
                        .HasForeignKey("loja_api.domain.Entities.Paymant", "CupomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("loja_api.domain.Entities.User", "User")
                        .WithMany("Paymant")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("loja_api.domain.Entities.auxiliar.Attdata", "AttDate", b1 =>
                        {
                            b1.Property<string>("PaymantId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Assunto")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Data")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PaymantId");

                            b1.ToTable("Paymant");

                            b1.WithOwner()
                                .HasForeignKey("PaymantId");
                        });

                    b.Navigation("AttDate")
                        .IsRequired();

                    b.Navigation("Cupom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("loja_api.domain.Entities.Products", b =>
                {
                    b.OwnsOne("loja_api.domain.Entities.auxiliar.Auditable", "Auditable", b1 =>
                        {
                            b1.Property<Guid>("ProductsIdProducts")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreateDate")
                                .HasColumnType("datetime2");

                            b1.Property<int>("CreatebyId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("UpdateDate")
                                .HasColumnType("datetime2");

                            b1.Property<int>("UpdatebyId")
                                .HasColumnType("int");

                            b1.HasKey("ProductsIdProducts");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductsIdProducts");
                        });

                    b.Navigation("Auditable")
                        .IsRequired();
                });

            modelBuilder.Entity("loja_api.domain.Entities.Storage", b =>
                {
                    b.HasOne("loja_api.domain.Entities.Products", "Products")
                        .WithMany("Storages")
                        .HasForeignKey("IdProducts")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("loja_api.domain.Entities.auxiliar.Auditable", "Auditable", b1 =>
                        {
                            b1.Property<Guid>("StorageIdStorage")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreateDate")
                                .HasColumnType("datetime2");

                            b1.Property<int>("CreatebyId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("UpdateDate")
                                .HasColumnType("datetime2");

                            b1.Property<int>("UpdatebyId")
                                .HasColumnType("int");

                            b1.HasKey("StorageIdStorage");

                            b1.ToTable("Storage");

                            b1.WithOwner()
                                .HasForeignKey("StorageIdStorage");
                        });

                    b.Navigation("Auditable")
                        .IsRequired();

                    b.Navigation("Products");
                });

            modelBuilder.Entity("loja_api.domain.Entities.auxiliar.ProductsPaymant", b =>
                {
                    b.HasOne("loja_api.domain.Entities.Products", "Products")
                        .WithMany("ProductsPaymant")
                        .HasForeignKey("IdProducts")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("loja_api.domain.Entities.Paymant", "Paymant")
                        .WithMany("ProductsPaymant")
                        .HasForeignKey("MarketCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paymant");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("loja_api.domain.Entities.Paymant", b =>
                {
                    b.Navigation("ProductsPaymant");
                });

            modelBuilder.Entity("loja_api.domain.Entities.Products", b =>
                {
                    b.Navigation("ProductsPaymant");

                    b.Navigation("Storages");
                });

            modelBuilder.Entity("loja_api.domain.Entities.User", b =>
                {
                    b.Navigation("Paymant");
                });
#pragma warning restore 612, 618
        }
    }
}
